[package]
name = "lethe_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twizzler-object = {path = "../../lib/twizzler-object"}
twizzler-abi = {path = "../../lib/twizzler-abi"}
persistence = { git = "https://github.com/lemosyne/persistence" }
allocator = { git = "https://github.com/lemosyne/allocator" }
lethe = { path = "external/lethe" }
embedded-io = { git = "https://github.com/euugenechou/embedded-io.git", features = ["std"] }
bitmap = "3.1.3"
naming = { git = "https://github.com/lemosyne/naming.git" }
serde = "1.0.186"
thiserror = "1.0.40"
num-traits = "0.2.15"
hasher = { git = "https://github.com/lemosyne/hasher.git" }
crypter = { git = "https://github.com/lemosyne/crypter.git"}
rand = "0.8.5"
orion = "0.15.4"
sha3 = "0.10.8"
anyhow = "1.0.71"
bincode = "1.3.3"
khf = { git = "https://github.com/lemosyne/khf.git" }
fute = { path = "../fute" }