[package]
name = "naming-test"
version = "0.1.0"
edition = "2021"

[dependencies]
twizzler-abi = { path = "../../lib/twizzler-abi" }
twizzler-object = { path = "../../lib/twizzler-object" }
twizzler-runtime = { path = "../../rt" }
naming = { path = "../../lib/naming" }
