[package]
name = "uuhelper"
version = "0.1.0"
edition = "2021"

[dependencies]
echo = { version = "0.0.28", package = "uu_echo", path = "../../../../coreutils/src/uu/echo" }
cat = { version = "0.0.28", package = "uu_cat", path = "../../../../coreutils/src/uu/cat" }
ls = { version = "0.0.28", package = "uu_ls", path = "../../../../coreutils/src/uu/ls" }
yes = { version = "0.0.28", package = "uu_yes", path = "../../../../coreutils/src/uu/yes" }
sort = { version = "0.0.28", package = "uu_sort", path = "../../../../coreutils/src/uu/sort" }

uucore = { version = "0.0.28", package = "uucore", path = "../../../../coreutils/src/uucore" }

[patch.crates-io]
