[package]
name = "observer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twizzler-abi = { path = "../../lib/twizzler-abi", features = ["runtime"] }
tracing = { version = "0.1.38", default-features = false, features = ['attributes'] }
tracing-subscriber = { version = "0.3", default-features = false }
twizzler-object = {path = "../../lib/twizzler-object"}
bumpalo = "3.15.4"

[package.metadata]
twizzler-build = "static"
